### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by ejb034** [Bucknell-Biol364/Project_1_Group_6_2024#1]
https://github.com/Bucknell-Biol364/Project_1_Group_6_2024/blob/3dc4c600040b5e26ab2b86c24cdf82b89099b401/FinalProject01.Rmd#L94

I got an error when I ran the code through, it just indicated that x had to be numeric ("Error in hist.default(x) : 'x' must be numeric"). I am not sure if that error is just on my side, but I'd check it out to make sure it goes through properly.

**Comment by JesseGunn** [comment]
Thank you for the catch!
